[package]
name = "rust"
version = "0.1.0"
authors = ["Peacess <peacess@163.com>"]
edition = "2018"
resover = "2"

[lib]
name = "rust"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[[bin]]
name = "async_order"
path = "src/async_thread/order_.rs"

[[bin]]
name = "trait"
path = "src/trait_/trait_object_.rs"

[[bin]]
name = "demo_2022_0226"
path = "src/demo_2022_0226/demo1.rs"

[dependencies]
lazy_static = "1.4.0"
once_cell = "*"
static_init = "*"
tokio = { version = "1.12.0", features = ["full"] }
num_cpus = "1.13.1"
libc = "0.2.122"
cargo-valgrind = "2.1.0"

futures = "*"

[dev-dependencies]

#block_on
futures = "*"
async-std = "*"
futures-lite = "*"
tokio = { version = "*", features = ["full"] }
smol = "*"
extreme = "*"

async-task = "*"
waker-fn = "*"
pin-utils = "*"
crossbeam = "*"
#end block_on

futures-io = "0.3.19"

[workspace]
members = ["rust_kits","demo/bench_block_on"]
