[package]
name = "rust"
version = "0.1.0"
authors = ["Peacess <peacess@163.com>"]
edition = "2021"

[lib]
name = "rust"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[[bin]]
name = "http_"
path = "src/net_/http_.rs"

[[bench]]
name = "bench_block_on"
path = "src/async_thread/block_on_.rs"
harness = false

[dependencies]
lazy_static = "*"
once_cell = "*"
static_init = "*"
tokio = { version = "*", features = ["full"] }
num_cpus = "*"
libc = "*"

crossbeam-channel = "0.5"

futures = "*"
crossbeam = "*"
async-task = "*"
waker-fn = "*"
pin-utils = "*"
async-std = "*"
futures-lite = "*"
smol = "*"
extreme = "*"

criterion = { version = "0.4.0", features = ["html_reports"] }

[dev-dependencies]
futures-io = "*"

[workspace]
members = ["./","rust_kits", "demo/bench_block_on", "demo/fn_gen_trait_closure"]
