[package]
name = "rust"
version = "0.1.0"
authors = ["Peacess <peacess@163.com>"]
edition = "2018"
resover="2"

[lib]
name = "rust"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[dependencies]
lazy_static = "1.4.0"
once_cell = "*"
static_init = "*"
tokio = { version="1.12.0", features = ["full"] }

[dev-dependencies]

#block_on
futures = "*"
async-std = "*"
futures-lite = "*"
tokio = { version="*", features = ["full"] }
smol = "*"
extreme="*"

async-task="*"
waker-fn ="*"
pin-utils="*"
crossbeam="*"
#end block_on

futures-io = "0.3.19"