
[workspace]
resolver = "2"
members = ["rust","rust_kits", "demo/bench_block_on", "demo/fn_gen_trait_closure", "crates/dashmap_", "demo/ffi"]

[workspace.package]
version = "0.1.7"
edition = "2021"
authors = ["Andy <peacess@163.com>"]
