[package]
name = "rust_kits"
version = "0.1.2"
edition = "2021"
authors = ["Andy <peacess@163.com>"]
description = "rust tool kits"
repository = "https://github.com/peacess/rust"
homepage = "https://github.com/peacess/rust"
keywords = ["rust", "kits"]
categories = ["concurrency"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.6.0"
bytemuck = "1.16.0"
walkdir = "2.5.0"
clap = { version = "4.5.4", features = ["derive"] }