[package]
name = "extreme_performance_"
description = "extreme single pc performance"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
core_affinity = "0.8.1"
